name: Rails CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: password
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install dependencies
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      env:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run tests with code coverage
      env:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: COVERAGE=true bundle exec rake test

    - name: Install Code Climate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
      working-directory: ${{ github.workspace }}
    - name: Push coverage data to Code Climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
      working-directory: ${{ github.workspace }}
