name: Rails CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
env:
  CI: true
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: password
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3

    - name: Install dependencies
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up database
      env:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: bundle exec rails test

    - name: Run tests with code coverage
      run: COVERAGE=true bundle exec rake test
